### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by djacouma** [lcdservices/JomSocial-Group-Sync#8]
Hey - This is brilliant but looks like it stopped at beta1 over 7 months ago.  Did project get moved?  Is there a working version for J25?  Happy to pay. Thanks!

**Comment by lcdservices** [comment]
this version is compatible with J25.
it's currently in production on some sites. I left it in a beta version state because there is one gap due to the absence of a trigger in jomsocial -- we've requested they fix it, but have not heard when that will happen.

**Comment by djacouma** [comment]
Thanks -- to clarify though, what does absence of trigger mean?  When someone joins a group through frontend in Jomsocial, doesn't it add them to same group in ACL, and if so is equivalence established by name or is here an ID table?  Sorry for questions but can't seem to find any info anywhere on this - shockingly, since I see this as a key/core feature for jomsocial.

**Comment by klapifoch** [comment]
Is this still compatible with Joomla 3.x and Jomsocial 4.x?

**Comment by lcdservices** [comment]
I've not done any testing with recent versions. It's worth trying (on a dev site environment), but I can't guarantee it will work.

**Comment by klapifoch** [comment]
I modified all files in order to install it under Joomla 3. Right now I am using jomsocial 4. I was able to link user groups against jomsocial group. But when I tried to click on join group nothing happen. It's like the hook isn't working. Can you explain exactly the version you tried this? Also I would like to know if all this code should be generate a record on user group map table, am I right? Thank you for your help!

**Comment by lcdservices** [comment]
honestly, I've not worked with this extension for some time. the client that sponsored the work was using v2.5 with JomSocial 2.6. it likely needs an overhaul to be compatible with current versions.
